
* Koester and Johnston 2005
 - Multiple release sites for the same connection have similar release
   probability.
 - Same release probability Pr at all N sites, quantal content q
   varies between sites, q_1 ... q_N. CV(q) = 0.2.

* Schubert, Ko"tter and Staiger
 - has a lot of information on connectivity, especially Figure 4.

* Feldmeyer, Lu"bke and Sakmann 2006
 - L2/3 Pyramidal to Pyramidal connections
   N = 2-4
   Average failure rate: 3.2 +/- 7.8 %,    Pr > 98% for 75% pairs
   V_0 = -76 +/- 4 mV
   V_th = -35 mV
** EPSP:
   tau_rise = 0.7 +/- 0.2 ms
   tau_decay = 15.7 +/- 4.5 ms
   amplitude = 1.0 +/- 0.7 mV
   
** EPSC:
   tau_rise = 0.35 +/- 0.6 ms
   tau_decay = 3.7 +/- 1.2 ms
   amplitude = 58 +/- 35 pA


   

* Leora Sarid, Randy Bruno, Bert Sakmann, Idan Segev, and Dirk Feldmeyer
  They modeled L4->L2/3 connections but the synaptic release
  probabilities were incorporated as stochastic input, not as
  facilitating synapse model. 

  Good info on EPSP models thoough.

* Alex Loebel, Gilad Silberberg, Daniela Helbig, Henry Markram, Misha Tsodyks and Magnus J. E. Richardson
  L5 Pyr->Pyr depression model in terms of variability of N, the
  number of release sites.

* Depression:
  Occurs in cortico-thalamic synapses (Diasynou Fioravante and Wade G
  Regehr, Short-term forms of presynaptic plasticity, Current Opinion
  in Neurobiology 2011, 21:1–6, DOI 10.1016/j.conb.2011.02.003)

* Lefort, S., Tomm, C., Floyd Sarria, J.-C. & Petersen, C.C.H. The Excitatory Neuronal Network of the C2 Barrel Column in Mouse Primary Somatosensory Cortex. Neuron 61, 301-316 (2009).
  Information on connectivity, but not release probability or synaptic
  parameters.

* Morrison, A., Diesmann, M. & Gerstner, W. Phenomenological models of synaptic plasticity based on spike timing. Biol Cybern 98, 459-478 (2008).
  Review of short term plasticity (facilitation and depression)

* Thomson, A.M. Activity-dependent properties of synaptic transmission at two classes of connections made by rat neocortical pyramidal axons in vitro. J. Physiol. (Lond.) 502 ( Pt 1), 131-147 (1997).
  This does not give the quantal parameters but says that
  Pyramid-Pyramid short term plasticities and pyramid-interneuron
  short term plasticities remain similar across different areas and
  different cells.

* Pan, B. & Zucker, R.S. A General Model of Synaptic Transmission and Short-Term Plasticity. Neuron 62, 539-554 (2009).

  Makes a detailed model of pre and postsynaptic mechanisms for short
  term plasticity in cray fish neurons.

  The above two papers introduced me to the new keywords: phasic and tonic synapse.


