#!/bin/bash
# 
# This script is for running multiple instances of the network on different nodes in a cluster 
# - specified in the file named `hostfile` in this directory.
# It simply runs the same python script, trbsim.py on each specified node. 
#
# The random-number generator is seeded with an integer generated by 
# numpy.random.randint(). We use an explicit seed and keep it for reproducibility. 
# This ensures each process has a different rng state and thus produces 
# a different network with the same connection probabilities and other 
# statistical properties.
#
# PYMOOSE_DIR is the location of the moose python module.
# PYTHON is the path to the python executable
PYMOOSE_DIR=/home/subhasis/moose_trunk_20131016/python
PYTHON=/usr/local/bin/python2.7
mpirun -x LD_LIBRARY_PATH -x PYTHONPATH=$PYTHONPATH:$PYMOOSE_DIR -hostfile hostfile $PYTHON trbsim.py -n "Running 70db lognormal on `hostname`"

